import {
    NbActionsModule,
    NbButtonModule,
    NbCardModule,
    NbCheckboxModule,
    NbContextMenuModule,
    NbDatepickerModule,
    NbDialogModule,
    NbFormFieldModule,
    NbIconModule,
    NbInputModule,
    NbLayoutModule,
    NbListModule,
    NbMenuModule,
    NbPopoverModule,
    NbSelectModule,
    NbSidebarModule,
    NbSpinnerModule,
    NbStepperModule,
    NbTimepickerModule,
    NbToastrModule,
    NbTreeGridModule,
    NbUserModule,
    NbToggleModule,
    NbTooltipModule,
    NbAutocompleteModule,
    NbTabsetModule,
    NbRouteTabsetModule,
    NbAlertModule,
    NbWindowModule,
    NbRadioModule
} from '@nebular/theme';
import { NbEvaIconsModule } from '@nebular/eva-icons';
import { MglTimelineModule } from 'angular-mgl-timeline';

export const NEBULAR_ROOT_MODULE = [NbMenuModule.forRoot(), NbDialogModule.forRoot(), NbToastrModule.forRoot(), NbSidebarModule.forRoot(), NbDatepickerModule.forRoot(), NbTimepickerModule.forRoot(), NbWindowModule.forRoot()];

export const NEBULAR_COMPONENTS_MODULE = [
    NbEvaIconsModule,
    NbLayoutModule,
    NbActionsModule,
    NbIconModule,
    NbMenuModule,
    NbPopoverModule,
    NbButtonModule,
    NbSidebarModule,
    NbContextMenuModule,
    NbInputModule,
    NbUserModule,
    NbDialogModule,
    NbTreeGridModule,
    NbSelectModule,
    NbCheckboxModule,
    NbFormFieldModule,
    NbCardModule,
    NbSpinnerModule,
    NbToastrModule,
    NbListModule,
    NbStepperModule,
    MglTimelineModule,
    NbDatepickerModule,
    NbTimepickerModule,
    NbToggleModule,
    NbTooltipModule,
    NbAutocompleteModule,
    NbTabsetModule,
    NbRouteTabsetModule,
    NbAlertModule,
    NbRadioModule
];
